# Generated by Django 5.2.6 on 2025-09-13 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ppi', 'PPI Task'), ('review', 'Review Meeting'), ('issue', 'Issue Resolution')], default='manual', max_length=20)),
                ('action', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('original_due_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('at_risk', 'At Risk'), ('danger', 'Danger'), ('done', 'Done'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='not_started', max_length=20)),
                ('revised_due_date', models.DateField(blank=True, null=True)),
                ('challenge', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_actions', to=settings.AUTH_USER_MODEL)),
                ('parent_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_actions', to='implement.action')),
                ('ppi_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.ppitask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.team')),
            ],
            options={
                'db_table': 'actions',
                'ordering': ['original_due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('revised_due_date', models.DateField(blank=True, null=True)),
                ('challenge', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='implement.action')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_history',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalated_to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_issues', to='organizations.team')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.team')),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumbersTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('fpi', 'FPI'), ('gpi', 'GPI')], max_length=3)),
                ('tracking_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('month_number', models.IntegerField(blank=True, null=True)),
                ('last_period_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_period_plan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_period_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('next_period_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('next_period_plan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fpi_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.fpiparameter')),
                ('gpi_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.gpiparameter')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.team')),
            ],
            options={
                'db_table': 'numbers_tracking',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('danger', 'Danger'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revised_due_date', models.DateField(blank=True, null=True)),
                ('challenge', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='plans.ppiproject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_status',
                'ordering': ['-updated_at'],
            },
        ),
    ]
