# Generated by Django 5.2.6 on 2025-09-19 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implement', '0001_initial'),
        ('improve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='improvement_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='improve.improvementtask'),
        ),
        migrations.AlterField(
            model_name='action',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ppi', 'PPI Task'), ('improvement', 'Improvement Task'), ('review', 'Review Meeting'), ('issue', 'Issue Resolution')], default='manual', max_length=20),
        ),
    ]
