# Generated by Django 5.2.6 on 2025-12-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implement', '0011_add_action_reassignment_model'),
        ('plans', '0011_remove_gpimonthlyrecord_unique_gpi_monthly_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('at_risk', 'At Risk'), ('danger', 'Danger'), ('overdue', 'Overdue'), ('done', 'Done'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('carry_forward', 'Carry Forward'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], help_text='Previous status before on_hold or dropped', max_length=20),
        ),
        migrations.AddField(
            model_name='action',
            name='quarter_number',
            field=models.IntegerField(blank=True, help_text='Quarter number (1-4) for quarterly tracking', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='quarter_number',
            field=models.IntegerField(blank=True, help_text='Quarter number (1-4) for quarterly tracking', null=True),
        ),
        migrations.AddField(
            model_name='numberstracking',
            name='ppi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.ppiproject'),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('at_risk', 'At Risk'), ('danger', 'Danger'), ('overdue', 'Overdue'), ('done', 'Done'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('carry_forward', 'Carry Forward'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='numberstracking',
            name='source_type',
            field=models.CharField(choices=[('gpi', 'GPI'), ('ppi', 'PPI')], max_length=3),
        ),
    ]
