# Generated by Django 5.2.6 on 2025-09-13 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'financial_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PPIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completion_criteria', models.TextField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ppi_projects',
            },
        ),
        migrations.CreateModel(
            name='PPITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('week_number', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plans.ppiproject')),
            ],
            options={
                'db_table': 'ppi_tasks',
            },
        ),
        migrations.CreateModel(
            name='QuarterlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='quarterly_plans/')),
                ('upload_status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed')], max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.financialyear')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_plans', to='organizations.team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quarterly_plans',
                'ordering': ['-uploaded_at'],
                'unique_together': {('team', 'financial_year', 'quarter')},
            },
        ),
        migrations.AddField(
            model_name='ppiproject',
            name='quarterly_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppi_projects', to='plans.quarterlyplan'),
        ),
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='annual_plans/')),
                ('upload_status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed')], max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_plans', to='organizations.team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.financialyear')),
            ],
            options={
                'db_table': 'annual_plans',
                'ordering': ['-uploaded_at'],
                'unique_together': {('team', 'financial_year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ppiproject',
            unique_together={('quarterly_plan', 'name')},
        ),
        migrations.CreateModel(
            name='GPIParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('tracking_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('indicator_type', models.CharField(choices=[('goal', 'Goal'), ('progress', 'Progress')], max_length=10)),
                ('quarter_goal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarterly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpi_parameters', to='plans.quarterlyplan')),
            ],
            options={
                'db_table': 'gpi_parameters',
                'unique_together': {('quarterly_plan', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FPIParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_head', models.CharField(choices=[('revenue', 'Revenue'), ('variable_cost', 'Variable Cost'), ('operating_expenses', 'Operating Expenses'), ('other_expenses', 'Other Expenses')], max_length=20)),
                ('sub_head', models.CharField(max_length=255)),
                ('quarter_goal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('month1_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('month2_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('month3_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarterly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpi_parameters', to='plans.quarterlyplan')),
            ],
            options={
                'db_table': 'fpi_parameters',
                'unique_together': {('quarterly_plan', 'sub_head')},
            },
        ),
    ]
