# Generated by Django 5.2.6 on 2025-09-14 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppiproject',
            old_name='due_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='fpiparameter',
            name='annual_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fpiparameter',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fpiparameter',
            name='quarter_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fpiparameter',
            name='ytd_till_last_quarter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='annual_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='quarter_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='ytd_till_last_quarter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ppiproject',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ppiproject',
            name='steps',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fpiparameter',
            name='month1_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fpiparameter',
            name='month2_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fpiparameter',
            name='month3_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='gpiparameter',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='AnnualFPIParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_head', models.CharField(choices=[('revenue', 'Revenue'), ('variable_cost', 'Variable Cost'), ('operating_expenses', 'Operating Expenses'), ('other_expenses', 'Other Expenses')], max_length=20)),
                ('sub_head', models.CharField(max_length=255)),
                ('annual_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q1_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q2_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q3_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q4_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpi_parameters', to='plans.annualplan')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annual_fpi_parameters',
                'unique_together': {('annual_plan', 'sub_head')},
            },
        ),
        migrations.CreateModel(
            name='AnnualGPIParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indicator_type', models.CharField(choices=[('goal', 'Goal'), ('progress', 'Progress')], max_length=10)),
                ('tracking_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('annual_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q1_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q2_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q3_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('q4_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpi_parameters', to='plans.annualplan')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annual_gpi_parameters',
                'unique_together': {('annual_plan', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AnnualPPIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('annual_goal', models.TextField(blank=True)),
                ('q1_goal', models.TextField(blank=True)),
                ('q2_goal', models.TextField(blank=True)),
                ('q3_goal', models.TextField(blank=True)),
                ('q4_goal', models.TextField(blank=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppi_projects', to='plans.annualplan')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annual_ppi_projects',
                'unique_together': {('annual_plan', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FPIMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField()),
                ('budget_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fpi_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='plans.fpiparameter')),
            ],
            options={
                'db_table': 'fpi_milestones',
                'unique_together': {('fpi_parameter', 'month_number')},
            },
        ),
        migrations.CreateModel(
            name='GPIMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('budget_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gpi_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='plans.gpiparameter')),
            ],
            options={
                'db_table': 'gpi_milestones',
                'unique_together': {('gpi_parameter', 'period_number')},
            },
        ),
    ]
