# Generated by Django 5.2.6 on 2025-09-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_fpiparameter_current_month_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpiparameter',
            name='last_month_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Previous month's current_month_plan value", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='last_month_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Previous month's current_month_plan value", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='last_week_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Previous week's current_week_plan value", max_digits=15, null=True),
        ),
    ]
