# Generated by Django 5.2.6 on 2025-12-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_team_options_alter_team_quarter'),
        ('plans', '0010_add_ppi_tracking_and_remove_fpi'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gpimonthlyrecord',
            name='unique_gpi_monthly_record',
        ),
        migrations.RemoveConstraint(
            model_name='gpiweeklyrecord',
            name='unique_gpi_weekly_record',
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='assigned_team',
            field=models.ForeignKey(blank=True, help_text='Team selected during reassignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gpi_parameters', to='organizations.team'),
        ),
        migrations.AlterUniqueTogether(
            name='gpimonthlyrecord',
            unique_together={('gpi_parameter', 'month_number')},
        ),
        migrations.AlterUniqueTogether(
            name='gpiweeklyrecord',
            unique_together={('gpi_parameter', 'week_number')},
        ),
    ]
