# Generated by Django 5.2.6 on 2025-09-18 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('plans', '0003_fpiparameter_current_month_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completion_criteria', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('steps', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('danger', 'Danger'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='on_track', max_length=20)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'improve_projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('week_number', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='improve.improvementproject')),
            ],
            options={
                'db_table': 'improve_tasks',
            },
        ),
        migrations.CreateModel(
            name='ImprovementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='improve_uploads/')),
                ('upload_status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('processing', 'Processing')], max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('error_records', models.IntegerField(default=0)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improve_uploads', to='plans.financialyear')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improve_uploads', to='organizations.team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improve_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'improve_uploads',
                'ordering': ['-uploaded_at'],
                'unique_together': {('team', 'financial_year', 'quarter')},
            },
        ),
        migrations.AddField(
            model_name='improvementproject',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='improve.improvementupload'),
        ),
        migrations.AlterUniqueTogether(
            name='improvementproject',
            unique_together={('upload', 'name')},
        ),
    ]
