# Generated by Django 5.2.6 on 2025-09-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_rename_due_date_ppiproject_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpiparameter',
            name='current_month_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fpiparameter',
            name='last_month_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='current_month_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='current_week_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='last_month_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gpiparameter',
            name='last_week_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
