# Generated by Django 5.2.6 on 2025-12-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_meeting_type_and_scheduling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['organization', 'name'], 'verbose_name': 'Team Meeting', 'verbose_name_plural': 'Team Meetings'},
        ),
        migrations.AlterField(
            model_name='team',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1 (Apr-Jun)'), ('Q2', 'Q2 (Jul-Sep)'), ('Q3', 'Q3 (Oct-Dec)'), ('Q4', 'Q4 (Jan-Mar)')], max_length=2, null=True),
        ),
    ]
