# Generated by Django 5.2.6 on 2025-09-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        # Add new columns to review_meetings table
        migrations.RunSQL(
            "ALTER TABLE review_meetings ADD COLUMN review_type varchar(10) DEFAULT 'weekly';",
            reverse_sql="ALTER TABLE review_meetings DROP COLUMN review_type;"
        ),
        migrations.RunSQL(
            "ALTER TABLE review_meetings ADD COLUMN review_date datetime;",
            reverse_sql="ALTER TABLE review_meetings DROP COLUMN review_date;"
        ),
        migrations.RunSQL(
            "ALTER TABLE review_meetings ADD COLUMN manager_name varchar(255) DEFAULT '';",
            reverse_sql="ALTER TABLE review_meetings DROP COLUMN manager_name;"
        ),
        migrations.RunSQL(
            "ALTER TABLE review_meetings ADD COLUMN created_by_id bigint;",
            reverse_sql="ALTER TABLE review_meetings DROP COLUMN created_by_id;"
        ),

        # Copy data from old columns to new columns
        migrations.RunSQL(
            "UPDATE review_meetings SET review_date = datetime(meeting_date, '12:00:00');",
            reverse_sql="UPDATE review_meetings SET meeting_date = date(review_date);"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET review_type = CASE WHEN meeting_type = 'weekly' THEN 'weekly' WHEN meeting_type = 'monthly' THEN 'monthly' ELSE 'daily' END;",
            reverse_sql="UPDATE review_meetings SET meeting_type = review_type;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET created_by_id = conducted_by_id WHERE conducted_by_id IS NOT NULL;",
            reverse_sql="UPDATE review_meetings SET conducted_by_id = created_by_id;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET manager_name = 'System' WHERE manager_name = '';",
            reverse_sql="UPDATE review_meetings SET manager_name = '';"
        ),
    ]
