# Generated by Django 5.2.6 on 2025-09-13 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implement', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('meeting_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_meetings', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_meetings', to='organizations.team')),
            ],
            options={
                'db_table': 'review_meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_meetings', to='implement.issue')),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues', to='review.reviewmeeting')),
            ],
            options={
                'db_table': 'review_issues',
                'unique_together': {('review_meeting', 'issue')},
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('decision', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='review.reviewmeeting')),
            ],
            options={
                'db_table': 'review_decisions',
                'ordering': ['serial_number'],
                'unique_together': {('review_meeting', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_meetings', to='implement.action')),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='review.reviewmeeting')),
            ],
            options={
                'db_table': 'review_actions',
                'unique_together': {('review_meeting', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='review.reviewmeeting')),
            ],
            options={
                'db_table': 'review_notes',
                'ordering': ['serial_number'],
                'unique_together': {('review_meeting', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='ReviewParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='review.reviewmeeting')),
            ],
            options={
                'db_table': 'review_participants',
                'unique_together': {('review_meeting', 'participant')},
            },
        ),
    ]
