# Generated by Django 5.2.6 on 2025-09-14 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('weekly', 'Weekly Review'), ('monthly', 'Monthly Review'), ('quarterly', 'Quarterly Review')], max_length=20)),
                ('meeting_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('month_number', models.IntegerField(blank=True, null=True)),
                ('quarter_number', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('key_decisions', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_meetings', to=settings.AUTH_USER_MODEL)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_meetings', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_meetings', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.financialyear')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_meetings', to='organizations.team')),
            ],
            options={
                'db_table': 'review_meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_type', models.CharField(choices=[('fpi', 'FPI Commitment'), ('gpi', 'GPI Commitment'), ('ppi', 'PPI Commitment'), ('other', 'Other Commitment')], max_length=20)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind', 'Behind Schedule'), ('completed', 'Completed')], default='on_track', max_length=20)),
                ('progress_notes', models.TextField(blank=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='reviews.reviewmeeting')),
            ],
            options={
                'db_table': 'review_commitments',
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='reviews.reviewmeeting')),
            ],
            options={
                'db_table': 'review_action_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('fpi', 'FPI Note'), ('gpi', 'GPI Note'), ('ppi', 'PPI Note'), ('issue', 'Issue Note'), ('general', 'General Note')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reviews.reviewmeeting')),
            ],
            options={
                'db_table': 'review_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
