# Generated by Django 5.2.6 on 2025-09-19 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implement', '0002_action_improvement_task_alter_action_source'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('review_date', models.DateTimeField()),
                ('manager_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='review_meetings_participated', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_meetings', to='organizations.team')),
            ],
            options={
                'db_table': 'review_meetings',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('due_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions_assigned', to='organizations.team')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions_created', to=settings.AUTH_USER_MODEL)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_action_items', to='reviews.reviewmeeting')),
            ],
            options={
                'db_table': 'review_action_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('decision', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='reviews.reviewmeeting')),
            ],
            options={
                'db_table': 'review_decisions',
                'ordering': ['serial_number'],
                'unique_together': {('review_meeting', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='ReviewCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_commitments', to='implement.action')),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='reviews.reviewmeeting')),
            ],
            options={
                'db_table': 'review_commitments',
                'unique_together': {('review_meeting', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('review_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='reviews.reviewmeeting')),
            ],
            options={
                'db_table': 'review_notes',
                'ordering': ['serial_number'],
                'unique_together': {('review_meeting', 'serial_number')},
            },
        ),
    ]
