# Generated by Django 5.2.6 on 2025-09-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20250919_1155'),
    ]

    operations = [
        # Copy data from new columns to old columns for compatibility
        migrations.RunSQL(
            "UPDATE review_meetings SET meeting_type = review_type WHERE review_type IS NOT NULL;",
            reverse_sql="UPDATE review_meetings SET review_type = meeting_type;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET meeting_date = date(review_date) WHERE review_date IS NOT NULL;",
            reverse_sql="UPDATE review_meetings SET review_date = datetime(meeting_date, '12:00:00');"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET conducted_by_id = created_by_id WHERE created_by_id IS NOT NULL;",
            reverse_sql="UPDATE review_meetings SET created_by_id = conducted_by_id;"
        ),

        # Set default values for old columns to handle NOT NULL constraints
        migrations.RunSQL(
            "UPDATE review_meetings SET meeting_type = 'weekly' WHERE meeting_type IS NULL;",
            reverse_sql="UPDATE review_meetings SET meeting_type = NULL;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET meeting_date = date('now') WHERE meeting_date IS NULL;",
            reverse_sql="UPDATE review_meetings SET meeting_date = NULL;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET status = 'scheduled' WHERE status IS NULL;",
            reverse_sql="UPDATE review_meetings SET status = NULL;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET summary = '' WHERE summary IS NULL;",
            reverse_sql="UPDATE review_meetings SET summary = NULL;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET key_decisions = '' WHERE key_decisions IS NULL;",
            reverse_sql="UPDATE review_meetings SET key_decisions = NULL;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET next_steps = '' WHERE next_steps IS NULL;",
            reverse_sql="UPDATE review_meetings SET next_steps = NULL;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET created_at = datetime('now') WHERE created_at IS NULL;",
            reverse_sql="UPDATE review_meetings SET created_at = NULL;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET updated_at = datetime('now') WHERE updated_at IS NULL;",
            reverse_sql="UPDATE review_meetings SET updated_at = NULL;"
        ),

        # Handle foreign key constraints
        migrations.RunSQL(
            "UPDATE review_meetings SET conducted_by_id = (SELECT id FROM users LIMIT 1) WHERE conducted_by_id IS NULL;",
            reverse_sql="UPDATE review_meetings SET conducted_by_id = NULL;"
        ),
        migrations.RunSQL(
            "UPDATE review_meetings SET financial_year_id = (SELECT id FROM financial_years LIMIT 1) WHERE financial_year_id IS NULL;",
            reverse_sql="UPDATE review_meetings SET financial_year_id = NULL;"
        ),

        # Create the missing participants many-to-many table
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS review_meetings_participants (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                reviewmeeting_id INTEGER NOT NULL,
                user_id INTEGER NOT NULL,
                FOREIGN KEY (reviewmeeting_id) REFERENCES review_meetings (id),
                FOREIGN KEY (user_id) REFERENCES users (id),
                UNIQUE (reviewmeeting_id, user_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS review_meetings_participants;"
        ),
    ]