# Generated by Django 5.2.6 on 2025-12-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implement', '0012_action_previous_status_action_quarter_number_and_more'),
        ('plans', '0011_remove_gpimonthlyrecord_unique_gpi_monthly_record_and_more'),
        ('reviews', '0005_add_assigned_to_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewnote',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='reviewcommitment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reviewnote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reviewactionitem',
            name='action',
        ),
        migrations.RemoveField(
            model_name='reviewactionitem',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='reviewactionitem',
            name='created_by',
        ),
        migrations.AddField(
            model_name='reviewactionitem',
            name='action_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reviewactionitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewactionitem',
            name='completion_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewactionitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewactionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviewcommitment',
            name='commitment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcommitment',
            name='committed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_commitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcommitment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcommitment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcommitment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcommitment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcommitment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewcommitment',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalized_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.financialyear'),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='is_adhoc',
            field=models.BooleanField(default=False, help_text='True if this is an ad-hoc meeting, False if cadence meeting'),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='key_decisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='month_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='next_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='quarter_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewmeeting',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewnote',
            name='note_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('action', 'Action'), ('decision', 'Decision'), ('follow_up', 'Follow Up')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewnote',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewactionitem',
            name='parameter_type',
            field=models.CharField(blank=True, choices=[('fpi', 'FPI'), ('gpi', 'GPI'), ('ppi', 'PPI'), ('issue', 'Issue')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reviewactionitem',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reviewcommitment',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_commitments', to='implement.action'),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewmeeting',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewmeeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewmeeting',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmeeting',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmeeting',
            name='review_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmeeting',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewnote',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
