# Generated by Django 5.2.6 on 2025-09-14 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='improvements/')),
                ('upload_status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('error_records', models.IntegerField(default=0)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.financialyear')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_uploads', to='organizations.team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'improvement_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='identified', max_length=20)),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_effort', models.CharField(blank=True, max_length=100)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='improvements.improvementupload')),
            ],
            options={
                'db_table': 'improvement_suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
